//bookings
INSERT INTO GAS_BOOKING.BOOKINGS
(BOOKINGID, BOOKING_DATE, GAS_TYPE, STATUS, CUSTOMER_ID, AGENCY_ID)
VALUES(1, '2025-07-19', 'LPG', 'CONFIRMED', 2, 1);
INSERT INTO GAS_BOOKING.BOOKINGS
(BOOKINGID, BOOKING_DATE, GAS_TYPE, STATUS, CUSTOMER_ID, AGENCY_ID)
VALUES(2, '2025-07-19', 'cng', 'PROCESSING', 2, 1);
INSERT INTO GAS_BOOKING.BOOKINGS
(BOOKINGID, BOOKING_DATE, GAS_TYPE, STATUS, CUSTOMER_ID, AGENCY_ID)
VALUES(3, '2025-07-19', 'LPG', 'PROCESSING', 3, 1);


//admins
INSERT INTO GAS_BOOKING.ADMINS
(ADMINID, PASSWORD, USERNAME)
VALUES(1, 'geetika', 'geetika');
INSERT INTO GAS_BOOKING.ADMINS
(ADMINID, PASSWORD, USERNAME)
VALUES(2, 'anil', 'anil');
INSERT INTO GAS_BOOKING.ADMINS
(ADMINID, PASSWORD, USERNAME)
VALUES(3, 'akshith', 'akshith');
INSERT INTO GAS_BOOKING.ADMINS
(ADMINID, PASSWORD, USERNAME)
VALUES(4, 'chaitanya', 'chaitanya');


//customer
INSERT INTO GAS_BOOKING.CUSTOMERS
(ID, EMAIL, NAME, PHONE)
VALUES(1, 'meera@example.com', 'Meera Sharma', '9123456780');
INSERT INTO GAS_BOOKING.CUSTOMERS
(ID, EMAIL, NAME, PHONE)
VALUES(2, 'geetika', 'suggu@gmail.com', '2568941527');
INSERT INTO GAS_BOOKING.CUSTOMERS
(ID, EMAIL, NAME, PHONE)
VALUES(3, 'akshith', 'akshith@gmail.com', '54614864644');
INSERT INTO GAS_BOOKING.CUSTOMERS
(ID, EMAIL, NAME, PHONE)
VALUES(4, 'anil', 'anil@gmail.com', '1234567890');
INSERT INTO GAS_BOOKING.CUSTOMERS
(ID, EMAIL, NAME, PHONE)
VALUES(5, 'chaitanya', 'chaitanya@gmail.com', '0987654321');
INSERT INTO GAS_BOOKING.CUSTOMERS
(ID, EMAIL, NAME, PHONE)
VALUES(6, 'raja@gmail.com', 'rajendra', '1488245457');
INSERT INTO GAS_BOOKING.CUSTOMERS
(ID, EMAIL, NAME, PHONE)
VALUES(8, 'a@gmail.com', 'a', '23654');
INSERT INTO GAS_BOOKING.CUSTOMERS
(ID, EMAIL, NAME, PHONE)
VALUES(7, 'maggie@gmail.com', 'meghana', '1488245457');

//GasAgency

INSERT INTO GAS_BOOKING.GAS_AGENCIES
(GASID, LOCATION, NAME)
VALUES(1, 'hyderabad', 'anilgasagency');

//payment

INSERT INTO GAS_BOOKING.PAYMENTS
(PAYMENTID, AMOUNT, PAYMENT_MODE, PAYMENT_STATUS, BOOKING_ID)
VALUES(201, 850.0, 'UPI', 'APPROVED', 1);
INSERT INTO GAS_BOOKING.PAYMENTS
(PAYMENTID, AMOUNT, PAYMENT_MODE, PAYMENT_STATUS, BOOKING_ID)
VALUES(202, 850.0, 'UPI', 'PENDING', 2);
INSERT INTO GAS_BOOKING.PAYMENTS
(PAYMENTID, AMOUNT, PAYMENT_MODE, PAYMENT_STATUS, BOOKING_ID)
VALUES(203, 850.0, 'UPI', 'PENDING', 3);